### ISSUE TITLE
What does the 52 week course look like?

### ISSUE THREAD

**Issue by ryantimjohn** [LambdaSchool/LambdaCSA-Syllabus#3]
I notice that, largely, y'all have two topics per week on the 26 week course. Is the 52 week course organized similarly to the 26 week course except with one topic per week? Would it make sense to make a separate syllabus for that?

**Comment by water-dao** [comment]
@ryantimjohn We don't yet have a point person for handling this kind of question here. I'm just a student. I asked internally about your question. I will try to follow up with more info or encourage someone else to.

**Comment by etisdew** [comment]
I hope that someone has gotten to you, if not feel free to email me at jschock16@gmail.com, but I ask you to close the issue once you have the information you need. The official syllabus is much like this however I would defer to the internal documentation and channels provided at the website. There has been a recent evolution in the curriculum that is not reflected in this and should be regarded as out of date. I am attempting to atleast maintain repo links for reference and iteration and as I understand the long course only buys you time to breath and think at the same time with the same curriculum.
